#  
# Copyright (C) 2016-2020 phantombot.github.io/PhantomBot
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

services:
  phantombot:
    container_name: phantombot
    # image: ghcr.io/phantombot/phantombot
    # image: porco/porcotwitch
    build: .
    restart: unless-stopped
    ports:
      - 25000:25000
    environment:
      # ------ Override any botlogin.txt variable here, with the PHANTOMBOT_ prefix
      # Twitch bot user (Required)
      PHANTOMBOT_USER: "PorcoRobot"
      # Twitch bot user OAuth token (https://phantombot.github.io/PhantomBot/oauth/) (Required)
      PHANTOMBOT_OAUTH: "3w32k54z0rc4cpe4vckkatanrc4cbj"
      # Twitch caster channel OAuth token (https://phantombot.github.io/PhantomBot/oauth/)
      PHANTOMBOT_APIOAUTH: "gk4mhf7gozczyjxt82n6xv272jnx4e"
      # Twitch caster channel (Required)
      PHANTOMBOT_CHANNEL: "touristegalactique"
      # Webinterface username
      PHANTOMBOT_PANELUSER: "PorcoRobotAdmin"
      # Webinterface password
      PHANTOMBOT_PANELPASSWORD: "7nO59m5@I4QfIe"
      # Webinterface use https? false (since caddy handles this)
      PHANTOMBOT_USEHTTPS: "false"
      PHANTOMBOT_PROXYBYPASSHTTPS: "true"
      # Enables EventSub
      PHANTOMBOT_USEEVENTSUB: "true"
      PHANTOMBOT_EVENTSUBCALLBACKURL: "https://twitch.crewlin-borgne.com/eventsub"
      # Indicates whether the bot is allowed to reload most JavaScript files when they are changed without a restart
      PHANTOMBOT_RELOADSCRIPTS: "true"
      # Indicates if Rollbar exception reporting is enabled
      PHANTOMBOT_USEROLLBAR: "true"
      # Indicates if the bots built-in webserver is enabled
      PHANTOMBOT_WEBENABLE: "true"
      # The TCP_NODELAY flag for TMI. Makes TMI less bandwidth efficient but possibly a little faster on outbound messages
      PHANTOMBOT_TWITCH_TCP_NODELAY: "true"
    volumes:
      # - phantombot_PhantomBot:/opt/PhantomBot
      - phantombot_PhantomBot_data:/opt/PhantomBot_data

volumes:
  # phantombot_PhantomBot:
  #   external: true
  phantombot_PhantomBot_data:
    external: true

networks:
  default:
    external:
      name: $APP_NETWORK